# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrcodeapp2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Title(object):
    def setupUi(self, Title):
        Title.setObjectName("Title")
        Title.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Title)
        self.centralwidget.setObjectName("centralwidget")
        self.ProgramTitle = QtWidgets.QLabel(self.centralwidget)
        self.ProgramTitle.setGeometry(QtCore.QRect(100, 50, 601, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ProgramTitle.setFont(font)
        self.ProgramTitle.setObjectName("ProgramTitle")
        self.RegCoca = QtWidgets.QLabel(self.centralwidget)
        self.RegCoca.setGeometry(QtCore.QRect(20, 140, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RegCoca.setFont(font)
        self.RegCoca.setObjectName("RegCoca")
        self.RegPepsi = QtWidgets.QLabel(self.centralwidget)
        self.RegPepsi.setGeometry(QtCore.QRect(20, 200, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RegPepsi.setFont(font)
        self.RegPepsi.setObjectName("RegPepsi")
        self.ReValCOCA = QtWidgets.QTextEdit(self.centralwidget)
        self.ReValCOCA.setGeometry(QtCore.QRect(250, 140, 71, 41))
        self.ReValCOCA.setObjectName("ReValCOCA")
        self.ReValPEPSI = QtWidgets.QTextEdit(self.centralwidget)
        self.ReValPEPSI.setGeometry(QtCore.QRect(250, 200, 71, 41))
        self.ReValPEPSI.setObjectName("ReValPEPSI")
        Title.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Title)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Title.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Title)
        self.statusbar.setObjectName("statusbar")
        Title.setStatusBar(self.statusbar)

        self.retranslateUi(Title)
        QtCore.QMetaObject.connectSlotsByName(Title)

    def retranslateUi(self, Title):
        _translate = QtCore.QCoreApplication.translate
        Title.setWindowTitle(_translate("Title", "MainWindow"))
        self.ProgramTitle.setText(_translate("Title", "QRCODE MANAGEMENT SYSTEM"))
        self.RegCoca.setText(_translate("Title", "Regconized COCA:"))
        self.RegPepsi.setText(_translate("Title", "Regconized PEPSI:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Title = QtWidgets.QMainWindow()
    ui = Ui_Title()
    ui.setupUi(Title)
    Title.show()
    sys.exit(app.exec_())
